name: e2e-test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_e2e_test:    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - run: make test-e2e
